{"name": "test_post_create_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'dict' object has no attribute 'json'", "trace": "self = <autotests.test_users.TestUsers object at 0x000001EF201C7390>\ncreate_and_delete_user = {'age': 30, 'first_name': 'Kimberly', 'job': 'Garment/textile technologist', 'last_name': 'Soto', ...}\nresponse_validator = <autotests.services.users.models.user_validation.ResponseValidator object at 0x000001EF20314E10>\n\n    @allure.story('Create user positive')\n    @pytest.mark.api_positive\n    def test_post_create_user(self, create_and_delete_user, response_validator):\n    \n>       assert response_validator.validate_positive_requests(create_and_delete_user.json(),'PostCreateUser')\nE       AttributeError: 'dict' object has no attribute 'json'\n\nautotests\\test_users.py:21: AttributeError"}, "start": 1753203895752, "stop": 1753203895753, "uuid": "ce2d913c-4251-4c4c-8109-893bbd6a0fab", "historyId": "d17486994c057395c4954952002e6ad1", "testCaseId": "d17486994c057395c4954952002e6ad1", "fullName": "test_users.TestUsers#test_post_create_user", "labels": [{"name": "feature", "value": "User API"}, {"name": "story", "value": "Create user positive"}, {"name": "tag", "value": "api_positive"}, {"name": "suite", "value": "test_users"}, {"name": "subSuite", "value": "TestUsers"}, {"name": "host", "value": "DESKTOP-KHTU12F"}, {"name": "thread", "value": "4228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_users"}]}